### ISSUE TITLE
About run env

### ISSUE THREAD

**Issue by drzhang3** [461054993/SDCN#1]
hello, could you please provide `requirements.txt`? and the Pytorch 's version?

**Comment by 461054993** [comment]
We have updated it. Thanks for the attention to our work.


The address is:&nbsp;https://github.com/461054993/SDCN.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"drzhang3"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月22日(星期六) 中午12:51
收件人:&nbsp;"461054993/SDCN"<SDCN@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[461054993/SDCN] About run env (#1)




hello, could you please provide requirements.txt? and the Pytorch 's version?

**Comment by drzhang3** [comment]
thanks

**Comment by drzhang3** [comment]
> We have updated it. Thanks for the attention to our work. The address is:&nbsp;https://github.com/461054993/SDCN.
> […](#)

thanks！
