### ISSUE TITLE
data和graph数据集之间的关系？

### ISSUE THREAD

**Issue by zhangyuanyang21** [461054993/SDCN#29]
你好请问data文件夹和graph文件夹里对应数据集的关系是什么呢？
![image](https://user-images.githubusercontent.com/85085067/163912734-fa793266-e509-470f-ad7a-e8192a2de602.png)
![image](https://user-images.githubusercontent.com/85085067/163912826-d93dd733-cc86-4a1c-b0ef-b9733b449431.png)
如：reut.pkl  reut.txt reut_lable.txt 和reut1_graph.txt reut3_graph.txt  reut5_graph.txt  之间的关系 ？reut1_graph.txt 是怎么由reut.txt 数据集得到的呢？

**Comment by lxhello** [comment]
同问

**Comment by handesome** [comment]
同问，有大佬做出来了吗
